Controllers/PerritosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Practica1.Models;
using Microsoft.AspNetCore.Http;
using System.IO;
using System.Text;
using Microsoft.AspNetCore.Mvc.Rendering;
using Practica1.ViewModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace Practica1.Controllers
{
    public class PerritosController : Controller
    {
        private AppDbContext _context;
        public static List<Perritos> ListaPerritos = null;
        public static List<Testimonios> ListaTesti = null;
        
        
        public PerritosController(AppDbContext context)
        {
            _context = context;
            /*var MiJson = System.IO.File.ReadAllText("Models/Perritos.json");
            ListaPerritos = JsonConvert.DeserializeObject<List<Perritos>>(MiJson);*/

            var MiJson = System.IO.File.ReadAllText("Models/Testimonios.json");
            ListaTesti = JsonConvert.DeserializeObject<List<Testimonios>>(MiJson);
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            var ListPerritos = await _context.Perritos.ToListAsync();

            return View(ListPerritos);
        }

        public async Task<IActionResult> Details(int Id)
        {
            var perrito = await _context.Perritos.Where(x => x.id == Id).Include(x => x.Interesados).FirstAsync();
            
            PerritosTestimoniosViewModel elem = new PerritosTestimoniosViewModel();

            List<Testimonios> testi = new List<Testimonios>();

            var random = new Random();
            int i = random.Next(0, 6);

            testi.Add(ListaTesti.ElementAt(i));
            i = random.Next(0, 6);
            testi.Add(ListaTesti.ElementAt(i));
            
            elem.Perrito = perrito;
            elem.Testimonios = testi;
            return View(elem);
        }

        public async Task<IActionResult> Find(string nombre)
        {
            var ListPerritos = await _context.Perritos.ToListAsync();
            List<Perritos> PerritosBuscados = new List<Perritos>();

            foreach (var dog in ListPerritos)
            {
                if(dog.Nombre.ToLower().Contains(nombre.ToLower())){
                    PerritosBuscados.Add(dog);
                }
            }

            return View("Index", PerritosBuscados);
        }

        public async Task<IActionResult> filtrar(string raza)
        {
            var ListPerritos = await _context.Perritos.ToListAsync();
            List<Perritos> PerritosBuscados = new List<Perritos>();

            foreach (var dog in ListPerritos)
            {
                if(String.Equals(dog.Raza, raza)){
                    PerritosBuscados.Add(dog);
                }
            }
            
            return View("Index", PerritosBuscados);
        }

        [Authorize(Roles = "Voluntario")]
        public IActionResult Add()
        {

            return View(new Perritos());
        }
        public async Task<IActionResult> Save(IFormCollection formCollection)
        {
            Perritos NuevoPerrito = NuevoPerrito = new Perritos();
            //var p = await _context.Perritos.ToListAsync();
            //NuevoPerrito.id = p.Last().id + 1;
            NuevoPerrito.Nombre = formCollection["Nombre"];
            NuevoPerrito.Raza = formCollection["Raza"];
            NuevoPerrito.Color = formCollection["Color"];
            NuevoPerrito.Edad = formCollection["Edad"];
            NuevoPerrito.Sexo = formCollection["Sexo"];
            NuevoPerrito.Salud = formCollection["Salud"];
            NuevoPerrito.Personalidad = formCollection["Personalidad"];
            NuevoPerrito.Descripcion = formCollection["Descripcion"];
            NuevoPerrito.Tema = formCollection["Tema"];


            if(formCollection.Files["Foto"].Length > 0){
                var NombreFoto = DateTime.Now.ToString("dd-MM-yyyy") + DateTime.Now.ToString("hh-mm-ss") + Path.GetFileName(formCollection.Files["Foto"].FileName);
                var path = Path.Combine(Path.GetFullPath("wwwroot/Images/Perritos"), NombreFoto);
                formCollection.Files["Foto"].CopyTo(new FileStream(path, FileMode.Create));
                NuevoPerrito.Foto = NombreFoto;
            }

            _context.Perritos.Add(NuevoPerrito);
            await _context.SaveChangesAsync();

            /*var JasonPerrito = JsonConvert.SerializeObject(ListaPerritos);

            var path2 = Path.GetFullPath("Models/Perritos.json");

            using (FileStream fr = System.IO.File.Create(path2, 1024))
            {
                byte[] jp = new UTF8Encoding(true).GetBytes(JasonPerrito);
                 fr.Write(jp, 0, jp.Length);
            }*/
            
            //ViewData["nom"] = "Se guardo ";
            return View("Index", await _context.Perritos.ToListAsync());
        }
        public IActionResult Requisitos()
        {
            return PartialView("~/Views/Perritos/Requisitos.cshtml");
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete (int id)
        {
            var perrito = await _context.Perritos.FindAsync(id);

            if (perrito == null){
                return NotFound();
            }
            
            _context.Remove(perrito);
            await _context.SaveChangesAsync();
            return View("Index", await _context.Perritos.ToListAsync());
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit (int id)
        {

            var perrito = await _context.Perritos.FindAsync(id);

            return View(perrito);

        }

        public async Task<IActionResult> Update (IFormCollection formCollection)
        {
            Perritos NuevoPerrito = NuevoPerrito = new Perritos();
            var perrito = await _context.Perritos.FindAsync(int.Parse(formCollection["id"]));
            
            //NuevoPerrito.id = int.Parse(formCollection["id"]);
            perrito.Nombre = formCollection["Nombre"];
            perrito.Raza = formCollection["Raza"];
            perrito.Color = formCollection["Color"];
            perrito.Edad = formCollection["Edad"];
            perrito.Sexo = formCollection["Sexo"];
            perrito.Salud = formCollection["Salud"];
            perrito.Personalidad = formCollection["Personalidad"];
            perrito.Descripcion = formCollection["Descripcion"];
            perrito.Tema = formCollection["Tema"];


            if(formCollection.Files["Foto"] != null){
                var NombreFoto = DateTime.Now.ToString("dd-MM-yyyy") + DateTime.Now.ToString("hh-mm-ss") + Path.GetFileName(formCollection.Files["Foto"].FileName);
                var path = Path.Combine(Path.GetFullPath("wwwroot/Images/Perritos"), NombreFoto);
                formCollection.Files["Foto"].CopyTo(new FileStream(path, FileMode.Create));
                perrito.Foto = NombreFoto;
            } 

            //_context.Perritos.Where(x => x.id == int.Parse(formCollection["id"]));
            _context.Perritos.Update(perrito);
            //_context.Remove(perrito);
            await _context.SaveChangesAsync();
            return View("Index", await _context.Perritos.ToListAsync());
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Dogcitos!</title>
    <link rel="shortcut icon" href="~/icono.ico">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/MisEstilos.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-secondary navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Dogcitos!</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <div>
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Perritos" asp-action="Index">Perritos en adopción</a>
                                </li>
                            </ul>
                        </div>
                        <div>
                            <partial name="_LoginPartial"/>
                        </div>
                    </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            Autor: Angie Jazmin Caballero Munguia
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutPerritos.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Dogcitos!</title>
    <link rel="shortcut icon" href="~/icono.ico">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/MisEstilos.css" />
</head>
<body class="bg-light">
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Dogcitos!</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <div>
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Perritos" asp-action="Index">Perritos en adopción</a>
                                </li>
                            </ul>
                        </div>
                        <div>
                            <partial name="_LoginPartial"/>
                        </div>
                    </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="row pb-12">
            <div class="col-md-12">
                @RenderSection("Arriba", false)
            </div>
            <div class="col-md-10">
                @RenderBody()
            </div>
            <div class="col-md-2">
            	@RenderSection("Derecha", false)
            </div>
 
            <div class="col-md-12">
            	@RenderSection("Abajo", false)
            </div>
        </main>

    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            Autor: Angie Jazmin Caballero Munguia
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/sweetalert.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>